name: panorama_viewer
description: Panorama Viewer - A 360-degree panorama viewer.
version: 1.0.1
homepage: https://github.com/dariocavada/panorama_viewer

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_cube: ^0.1.1

  #HintAzuma comment out
#  dchs_motion_sensors: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
